### ISSUE TITLE
bug in Hangul composition

### ISSUE THREAD

**Issue by dohyunkim** [zauguin/lua-uni-algos#1]
https://github.com/zauguin/lua-uni-algos/blob/70d8873e28a15b60096baae459c864053b9843de/lua-uni-normalize.lua#L236

It seems that `0x11A7` should be changed to `0x1175`. 
Otherwise, for instance the following gives quite unexpected output:
```tex
\directlua{
  local normalize=require"lua-uni-normalize"
  local str="^^^^1100^^^^119e^^^^11ab"
  print("", str, normalize.NFC(str))
}
\end
```
```
This is LuaTeX, Version 1.12.0 (TeX Live 2020)
 restricted system commands enabled.
(./t.tex	ᄀᆞᆫ	늰
)
```
which should be
```
(./t.tex	ᄀᆞᆫ	ᄀᆞᆫ
)
```

**Comment by zauguin** [comment]
Thank you, it's fixed now.

**Comment by zauguin** [comment]
Do you have some background on these? According to Unicode classifications, U+1176 to U+115F (and U+D7B0..D7C6 also have type "Vowel_Jamo", so what makes them different? Are they not used in the LV/LVT syllable structure or are their syllables just not encoded?

**Comment by dohyunkim** [comment]
A precompsed LV/LVT syllable (U+AC00..U+D7A3) is canonically composed of a Leading Consonant (U+1100..U+1112) and a Medial Vowel (U+1161..U+1175) and possibly a Trailing Consonant (U+11A8..U+11C2). 
These LV/LVT syllables are used for modern Hangul writing, whereas all other Hangul Jamo characters (not listed above) are used for expressing medieval Hangul. 
Unlike modern Hangul syllables, Unicode does not have precomposed medieval Hangul syllables.
